server:
  port: 10001

spring: 

  main:
    allow-bean-definition-overriding: true
    
    
  application:
    name: mountain-shop-redis
    
    
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080
        
        
        
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1



dubbo:
  application:
    name: mountain-shop-redis
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    basePackages: com.mountain.redis.api


feign:
  sentinel: 
    enabled: true



management:
  endpoints: 
    web: 
      exposure: 
        include: "*"